title: <p align="center"> Ayush Anand </p>
logo: <a href="https://www.google.com/url?sa=i&url=https%3A%2F%2Fin.linkedin.com%2Fin%2Fayush-anand-a09796a0&psig=AOvVaw1hNDknob1LW8gKDgenWKZl&ust=1685527263828000&source=images&cd=vfe&ved=0CA4QjRxqFwoTCPCihcHknP8CFQAAAAAdAAAAABAD">Profile Image</a>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ayush-anand-a09796a0/">LinkedIn</a> |
  <a href="https://github.com/anandayush315">GitHub</a>
  
  <br>   
  I'm responsile for IT sustainability in my company.
  Although I am a mechnaical engineer, but always had keen interest in coding.
  Worked with Faurecia and ZF group.
  Working in Automotive domain for 5 years.
  <br>
  </p>

theme: jekyll-theme-minimal
